version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: manageme-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: manageme
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network

  web:
    build:
      context: .
    container_name: manageme-web
    restart: always
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/manageme
    depends_on:
      - mongodb
    networks:
      - my-network

volumes:
  mongo_data:

networks:
  my-network: